const {chromium}=require('C:/Users/Raven 2400G/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const THREE=require('three');const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'chrome',args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const url='file:///E:/ChatGPT/TNB%20Bill/game-3d.html';await page.goto(url);await page.locator('[data-piece="plant"]').waitFor();await page.waitForTimeout(300);
async function point(p,cell,y=.18){const r=await p.locator('#board').boundingBox();const aspect=r.width/r.height,span=aspect<1?13.5/aspect:10.8;const c=new THREE.OrthographicCamera(-span*aspect/2,span*aspect/2,span/2,-span/2,.1,100);c.position.set(11,12,15);c.lookAt(0,.15,0);c.updateMatrixWorld();const v=new THREE.Vector3((cell.charCodeAt(0)-65-2.5)*1.4,y,(Number(cell[1])-1-2.5)*1.4).project(c);return{x:r.x+(v.x+1)/2*r.width,y:r.y+(-v.y+1)/2*r.height};}
async function drop(type,cell){const b=page.locator(`[data-piece="${type}"]`);await b.scrollIntoViewIfNeeded();const r=await b.boundingBox();const p=await point(page,cell);await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(p.x,p.y,{steps:15});await page.mouse.up();await page.waitForTimeout(150);}
async function next(){assert(await page.locator('#discovery').isVisible());await page.click('#next');await page.waitForTimeout(100);}
const label=cell=>page.locator(`[data-cell="${cell}"]`).getAttribute('aria-label');
await page.screenshot({path:'.qa/3d-initial.png',fullPage:true});
await drop('plant','F6');assert(!/Loji/.test(await label('B3')));assert.match(await page.locator('#feedback').innerText(),/Hampir/);
await drop('plant','B3');assert.match(await label('B3'),/Loji elektrik/);
await drop('fuel','B3');assert.equal(await page.locator('.story-card.unlocked').count(),1);await next();
await drop('station','D3');assert.match(await label('D3'),/Pencawang/);await drop('house','E5');assert.match(await page.locator('#boardToast').innerText(),/Lampu/);await next();
await page.screenshot({path:'.qa/3d-night.png',fullPage:true});await drop('backup','B5');assert.equal(await page.locator('.story-card.unlocked').count(),3);await next();
await drop('up','B3');assert.match(await page.locator('#boardToast').innerText(),/surcaj/);assert(!await page.locator('#discovery').isVisible());await drop('down','B3');assert.match(await page.locator('#boardToast').innerText(),/rebat/);await next();assert(await page.locator('#finish').isVisible());
await drop('solar','C5');assert.match(await label('C5'),/Panel solar/);await drop('tree','D5');assert.match(await label('D5'),/Pokok/);
await page.locator('#board').scrollIntoViewIfNeeded();let from=await point(page,'D5',1.1),to=await point(page,'D6');await page.mouse.move(from.x,from.y);await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:15});await page.mouse.up();await page.waitForTimeout(200);assert.match(await label('D6'),/Pokok/);assert.equal(await label('D5'),'Petak D5');
await page.screenshot({path:'.qa/3d-complete.png',fullPage:true});
const before=await page.locator('#board').screenshot();await page.click('#rotateLeft');await page.waitForTimeout(200);const after=await page.locator('#board').screenshot();assert(!before.equals(after),'Camera rotation changes rendered board');await page.click('#zoomIn');await page.click('#zoomOut');await page.click('#resetView');
await page.click('#restart');assert.equal(await page.locator('.story-card.unlocked').count(),0);assert.equal(await label('B3'),'Petak B3');
await page.locator('[data-piece="plant"]').focus();await page.keyboard.press('Enter');await page.locator('#cellPicker summary').click();await page.locator('[data-cell="B3"]').focus();await page.keyboard.press('Enter');assert.match(await label('B3'),/Loji/);await page.locator('[data-piece="fuel"]').focus();await page.keyboard.press('Enter');await page.keyboard.press('Escape');assert.equal(await page.locator('[data-piece="fuel"]').getAttribute('aria-pressed'),'false');
const mobile=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,reducedMotion:'reduce'});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(url);await mobile.locator('[data-piece="plant"]').waitFor();await mobile.waitForTimeout(300);await mobile.screenshot({path:'.qa/3d-mobile.png',fullPage:true});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('[data-piece="plant"]').scrollIntoViewIfNeeded();const a=await mobile.locator('[data-piece="plant"]').boundingBox(),b=await point(mobile,'B3');assert(b.y>0&&b.y<844);const ax=a.x+a.width/2,ay=a.y+a.height/2;const cdp=await mobile.context().newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:ax,y:ay}]});for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:ax+(b.x-ax)*i/12,y:ay+(b.y-ay)*i/12}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.match(await mobile.locator('[data-cell="B3"]').getAttribute('aria-label'),/Loji/);await mobile.waitForTimeout(450);await mobile.locator('[data-piece="fuel"]').tap();await mobile.locator('#targetHint').tap();assert.equal(await mobile.locator('.story-card.unlocked').count(),1);
const fallback=await browser.newPage();await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type.startsWith('webgl')?null:original.call(this,type,...args);};});await fallback.goto(url);await fallback.locator('#fallback').waitFor({state:'visible'});assert(await fallback.locator('#fallback a[href="game.html"]').isVisible());
await page.goto('file:///E:/ChatGPT/TNB%20Bill/index.html');await page.locator('a[href="game-3d.html"]').click();await page.locator('[data-piece="plant"]').waitFor();assert.deepEqual(errors,[]);
console.log('PASS: real WebGL rendering; invalid drop; all 4 stories via raycast drag; AFA +/-; free build and moving 3D pieces; camera rotate/zoom/reset; restart; keyboard placement/Escape; mobile touch drag/tap; responsive overflow; WebGL fallback; index link; no JS errors.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
